import 'dart:convert';
import 'package:flutter/material.dart';
import '../services/todo_service.dart';
import '../services/goal_service.dart';
import '../services/habit_service.dart';
import '../models/todo.dart';
import '../models/goal.dart';
import '../models/habit.dart';
import '../models/milestone.dart';
import '../components/empty_state.dart';

class TodoFacePage extends StatefulWidget {
  final TodoService todoService;
  final GoalService goalService;
  final HabitService habitService;

  const TodoFacePage({
    super.key,
    required this.todoService,
    required this.goalService,
    required this.habitService,
  });

  @override
  State<TodoFacePage> createState() => _TodoFacePageState();
}

class _TodoFacePageState extends State<TodoFacePage> {
  List<Todo> _todayTodos = [];
  List<Todo> _expiredTodos = [];
  List<Todo> _futureTodos = [];
  Map<int, String> _habitNames = {};
  Map<int, String> _goalNames = {};
  Map<int, String> _milestoneNames = {};
  bool _loading = true;
  final _newTodoController = TextEditingController();

  @override
  void initState() {
    super.initState();
    _loadData();
  }

  @override
  void dispose() {
    _newTodoController.dispose();
    super.dispose();
  }

  Future<void> _loadData() async {
    setState(() => _loading = true);
    try {
      final todos = await widget.todoService.getTodayTodos();
      final expired = await widget.todoService.getExpiredManualTodos();
      final future = await widget.todoService.getFutureManualTodos();

      // 加载关联名称
      final habitIds = <int>{};
      final goalIds = <int>{};
      final milestoneIds = <int>{};
      for (final t in [...todos, ...expired, ...future]) {
        if (t.habitId != null) habitIds.add(t.habitId!);
        if (t.goalId != null) goalIds.add(t.goalId!);
        if (t.milestoneId != null) milestoneIds.add(t.milestoneId!);
      }

      final habitNames = <int, String>{};
      final goalNames = <int, String>{};
      final milestoneNames = <int, String>{};
      for (final hid in habitIds) {
        final h = await widget.habitService.getHabit(hid);
        if (h != null) habitNames[hid] = h.name;
      }
      for (final gid in goalIds) {
        final g = await widget.goalService.getGoal(gid);
        if (g != null) goalNames[gid] = g.name;
      }
      for (final mid in milestoneIds) {
        final m = await widget.goalService.getMilestone(mid);
        if (m != null) milestoneNames[mid] = m.name;
      }

      if (!mounted) return;
      setState(() {
        _todayTodos = todos;
        _expiredTodos = expired;
        _futureTodos = future;
        _habitNames = habitNames;
        _goalNames = goalNames;
        _milestoneNames = milestoneNames;
        _loading = false;
      });
    } catch (_) {
      if (mounted) setState(() => _loading = false);
    }
  }

  Future<void> _toggleTodo(Todo todo, bool value) async {
    await widget.todoService.toggleTodo(todo.id!, value);
    _loadData();
  }

  Future<void> _deleteTodo(Todo todo) async {
    await widget.todoService.deleteTodo(todo.id!);
    _loadData();
  }

  Future<void> _postponeExpired() async {
    await widget.todoService.postponeExpiredTodos();
    _loadData();
  }

  Future<void> _addManualTodo(String title, {int? goalId, int? milestoneId, int? habitId, String? date, String? time}) async {
    if (title.trim().isEmpty) return;
    await widget.todoService.createManualTodo(
      title: title.trim(),
      goalId: goalId,
      milestoneId: milestoneId,
      habitId: habitId,
      date: date,
      time: time,
    );
    _newTodoController.clear();
    _loadData();
  }

  Future<void> _editTodo(Todo todo) async {
    final result = await showModalBottomSheet<TodoData>(
      context: context,
      isScrollControlled: true,
      builder: (ctx) => _TodoEditSheet(
        goalService: widget.goalService,
        habitService: widget.habitService,
        initialTitle: todo.title,
        initialGoalId: todo.goalId,
        initialMilestoneId: todo.milestoneId,
        initialHabitId: todo.habitId,
        initialDate: todo.date,
        initialTime: todo.time,
        isAutoGenerated: todo.isAutoGenerated,
        onSave: (title, goalId, milestoneId, habitId, date, time) => Navigator.pop(ctx, TodoData(
          title: title,
          goalId: goalId,
          milestoneId: milestoneId,
          habitId: habitId,
          date: date,
          time: time,
        )),
      ),
    );
    if (result == null || !mounted) return;
    await widget.todoService.updateTodo(todo.copyWith(
      title: result.title.trim(),
      goalId: result.goalId,
      milestoneId: result.milestoneId,
      habitId: result.habitId,
      date: result.date ?? todo.date,
      time: result.time,
    ));
    _loadData();
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    if (_loading) {
      return const Center(child: CircularProgressIndicator());
    }

    final completedCount = _todayTodos.where((t) => t.isCompleted).length;
    final totalCount = _todayTodos.length;
    final hasExpired = _expiredTodos.isNotEmpty;
    const hasFuture = true; // always check _futureTodos

    return Stack(
      children: [
        Column(
          children: [
            // ── Header: progress + 顺延 ──
            if (totalCount > 0 || hasExpired)
              Padding(
                padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
                child: Row(
                  children: [
                    if (totalCount > 0) ...[
                      Text(
                        '$completedCount/$totalCount 已完成',
                        style: TextStyle(
                          fontSize: 13,
                          color: colorScheme.onSurface.withValues(alpha: 0.6),
                        ),
                      ),
                      const SizedBox(width: 12),
                      Expanded(
                        child: ClipRRect(
                          borderRadius: BorderRadius.circular(4),
                          child: LinearProgressIndicator(
                            value: totalCount > 0 ? completedCount / totalCount : 0,
                            backgroundColor: colorScheme.outline.withValues(alpha: 0.1),
                            valueColor: AlwaysStoppedAnimation<Color>(
                              completedCount == totalCount && totalCount > 0
                                  ? Colors.green
                                  : colorScheme.primary,
                            ),
                            minHeight: 6,
                          ),
                        ),
                      ),
                    ] else
                      const Spacer(),
                    if (hasExpired) ...[
                      const SizedBox(width: 8),
                      FilledButton.tonalIcon(
                        onPressed: _postponeExpired,
                        icon: const Icon(Icons.event_repeat, size: 18),
                        label: const Text('顺延'),
                        style: FilledButton.styleFrom(
                          visualDensity: VisualDensity.compact,
                          padding: const EdgeInsets.symmetric(horizontal: 12),
                        ),
                      ),
                    ],
                  ],
                ),
              ),

            // ── Expired manual todos ──
            if (_expiredTodos.isNotEmpty) ...[
              Padding(
                padding: const EdgeInsets.fromLTRB(16, 12, 16, 0),
                child: Row(
                  children: [
                    Icon(Icons.history, size: 16, color: Colors.orange.shade700),
                    const SizedBox(width: 6),
                    Text(
                      '过期待办',
                      style: TextStyle(
                        fontSize: 13,
                        fontWeight: FontWeight.w600,
                        color: Colors.orange.shade700,
                      ),
                    ),
                  ],
                ),
              ),
              ..._expiredTodos.map((t) => _buildTodoTile(t, colorScheme, isExpired: true)),
              const Divider(indent: 16, endIndent: 16, height: 24),
            ],

            // ── Today's todos ──
            Expanded(
              child: _todayTodos.isEmpty && _expiredTodos.isEmpty && _futureTodos.isEmpty
                  ? const EmptyState(icon: Icons.checklist_outlined, message: '今天没有待办事项。\n好好休息或创建一个吧！')
                  : ListView(
                      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 4),
                      children: [
                        ..._buildGroupedTodos(colorScheme),

                        // ── Future todos (即将到来) ──
                        if (_futureTodos.isNotEmpty) ...[
                          if (_todayTodos.isNotEmpty) const Divider(indent: 0, endIndent: 0, height: 24),
                          Padding(
                            padding: const EdgeInsets.only(bottom: 4),
                            child: Row(
                              children: [
                                Icon(Icons.schedule_send, size: 16, color: Colors.blue.shade700),
                                const SizedBox(width: 6),
                                Text(
                                  '即将到来',
                                  style: TextStyle(
                                    fontSize: 13,
                                    fontWeight: FontWeight.w600,
                                    color: Colors.blue.shade700,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          for (final t in _futureTodos)
                            _buildTodoTile(t, colorScheme, isFuture: true),
                        ],

                        const SizedBox(height: 80),
                      ],
                    ),
            ),
          ],
        ),

        // ── FAB ──
        Positioned(
          right: 20,
          bottom: 20,
          child: FloatingActionButton(
            onPressed: _showAddTodoSheet,
            tooltip: '添加待办',
            child: const Icon(Icons.add),
          ),
        ),
      ],
    );
  }

  /// 将 Todo 分组显示：自动生成的按习惯分组，里程碑待办按里程碑分组，手动的单独
  List<Widget> _buildGroupedTodos(ColorScheme colorScheme) {
    final autoTodos = _todayTodos.where((t) => t.isAutoGenerated).toList();
    final milestoneTodos = _todayTodos.where((t) => !t.isAutoGenerated && t.milestoneId != null).toList();
    final manualTodos = _todayTodos.where((t) => !t.isAutoGenerated && t.milestoneId == null).toList();

    final widgets = <Widget>[];

    // ── 自动 Todo（按习惯分组）──
    if (autoTodos.isNotEmpty) {
      final grouped = <int?, List<Todo>>{};
      for (final t in autoTodos) {
        grouped.putIfAbsent(t.habitId, () => []).add(t);
      }

      for (final entry in grouped.entries) {
        final habitId = entry.key;
        final todos = entry.value;
        final habitName = habitId != null ? _habitNames[habitId] : null;

        widgets.add(
          Padding(
            padding: const EdgeInsets.only(top: 8, bottom: 4),
            child: Row(
              children: [
                Icon(Icons.repeat, size: 16, color: colorScheme.primary),
                const SizedBox(width: 6),
                Text(
                  habitName ?? '习惯',
                  style: TextStyle(
                    fontSize: 13,
                    fontWeight: FontWeight.w600,
                    color: colorScheme.primary,
                  ),
                ),
              ],
            ),
          ),
        );

        for (final t in todos) {
          widgets.add(_buildTodoTile(t, colorScheme));
        }
      }
    }

    // ── 里程碑待办（按里程碑分组）──
    if (milestoneTodos.isNotEmpty) {
      if (autoTodos.isNotEmpty) {
        widgets.add(const Divider(indent: 0, endIndent: 0, height: 24));
      }

      final grouped = <int?, List<Todo>>{};
      for (final t in milestoneTodos) {
        grouped.putIfAbsent(t.milestoneId, () => []).add(t);
      }

      for (final entry in grouped.entries) {
        final milestoneId = entry.key;
        final todos = entry.value;
        final milestoneName = milestoneId != null ? _milestoneNames[milestoneId] : null;
        // 取第一个 todo 的 goalId 来显示目标名
        final goalName = todos.first.goalId != null ? _goalNames[todos.first.goalId!] : null;
        final header = goalName != null && milestoneName != null
            ? '$goalName · $milestoneName'
            : milestoneName ?? '里程碑';

        widgets.add(
          Padding(
            padding: const EdgeInsets.only(top: 8, bottom: 4),
            child: Row(
              children: [
                Icon(Icons.flag, size: 16, color: colorScheme.secondary),
                const SizedBox(width: 6),
                Expanded(
                  child: Text(
                    header,
                    style: TextStyle(
                      fontSize: 13,
                      fontWeight: FontWeight.w600,
                      color: colorScheme.secondary,
                    ),
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
              ],
            ),
          ),
        );

        for (final t in todos) {
          widgets.add(_buildTodoTile(t, colorScheme));
        }
      }
    }

    // ── 手动待办（无里程碑关联）──
    if (manualTodos.isNotEmpty) {
      if (autoTodos.isNotEmpty || milestoneTodos.isNotEmpty) {
        widgets.add(const Divider(indent: 0, endIndent: 0, height: 24));
      }

      widgets.add(
        Padding(
          padding: const EdgeInsets.only(bottom: 4),
          child: Row(
            children: [
              Icon(Icons.edit_note, size: 16, color: colorScheme.tertiary),
              const SizedBox(width: 6),
              Text(
                '手动待办',
                style: TextStyle(
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                  color: colorScheme.tertiary,
                ),
              ),
            ],
          ),
        ),
      );

      for (final t in manualTodos) {
        widgets.add(_buildTodoTile(t, colorScheme));
      }
    }

    return widgets;
  }

  Widget _buildTodoTile(Todo todo, ColorScheme colorScheme, {bool isExpired = false, bool isFuture = false}) {
    final habitName = todo.habitId != null ? _habitNames[todo.habitId!] : null;
    final goalName = todo.goalId != null ? _goalNames[todo.goalId!] : null;

    return Dismissible(
      key: ValueKey('todo_${todo.id}'),
      direction: todo.isAutoGenerated
          ? DismissDirection.none
          : DismissDirection.endToStart,
      onDismissed: (_) => _deleteTodo(todo),
      background: Container(
        alignment: Alignment.centerRight,
        padding: const EdgeInsets.only(right: 16),
        color: Colors.red.shade100,
        child: Icon(Icons.delete, color: Colors.red.shade400),
      ),
      child: ListTile(
        dense: true,
        contentPadding: const EdgeInsets.symmetric(horizontal: 4),
        leading: Checkbox(
          value: todo.isCompleted,
          onChanged: (v) => _toggleTodo(todo, v ?? false),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
        ),
        title: Text(
          todo.title,
          style: TextStyle(
            decoration: todo.isCompleted ? TextDecoration.lineThrough : null,
            color: todo.isCompleted
                ? colorScheme.onSurface.withValues(alpha: 0.4)
                : isExpired
                    ? Colors.orange.shade800
                    : isFuture
                        ? Colors.blue.shade700
                        : null,
          ),
        ),
        subtitle: _buildSubtitle(todo, habitName, goalName, isExpired, isFuture),
        trailing: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            // 编辑按钮
            IconButton(
              icon: Icon(Icons.edit_outlined, size: 18,
                  color: colorScheme.onSurface.withValues(alpha: 0.4)),
              onPressed: () => _editTodo(todo),
              visualDensity: VisualDensity.compact,
              tooltip: '编辑',
              padding: const EdgeInsets.all(4),
              constraints: const BoxConstraints(minWidth: 32, minHeight: 32),
            ),
            if (todo.isAutoGenerated)
              Padding(
                padding: const EdgeInsets.only(right: 4),
                child: Icon(Icons.auto_mode, size: 16,
                    color: colorScheme.onSurface.withValues(alpha: 0.2)),
              )
            else
              const SizedBox(width: 4),
          ],
        ),
      ),
    );
  }

  Widget? _buildSubtitle(Todo todo, String? habitName, String? goalName, bool isExpired, [bool isFuture = false]) {
    final parts = <String>[];
    final today = DateTime.now();
    final todayStr = '${today.year}-${today.month.toString().padLeft(2, '0')}-${today.day.toString().padLeft(2, '0')}';
    if (todo.date != todayStr) {
      parts.add(todo.date);
    }
    if (todo.time != null) {
      parts.add('${todo.time!}');
    }
    if (isExpired) parts.add('过期');
    if (isFuture) parts.add('即将到来');
    if (habitName != null && !todo.isAutoGenerated) parts.add('习惯：$habitName');
    if (goalName != null && !todo.isAutoGenerated) parts.add('目标：$goalName');

    if (parts.isEmpty) return null;
    return Text(
      parts.join(' · '),
      style: TextStyle(
        fontSize: 11,
        color: isExpired ? Colors.orange.shade600 : (isFuture ? Colors.blue.shade600 : Colors.grey),
      ),
    );
  }

  // ── Add todo bottom sheet ──

  void _showAddTodoSheet() {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      builder: (ctx) => _TodoEditSheet(
        goalService: widget.goalService,
        habitService: widget.habitService,
        isAddMode: true,
        onSave: (title, goalId, milestoneId, habitId, date, time) {
          Navigator.pop(ctx);
          _addManualTodo(title, goalId: goalId, milestoneId: milestoneId, habitId: habitId, date: date, time: time);
        },
      ),
    );
  }
}

/// 用于在编辑/新建 sheet 和页面间传递数据
class TodoData {
  final String title;
  final int? goalId;
  final int? milestoneId;
  final int? habitId;
  final String? date;
  final String? time;
  TodoData({
    required this.title,
    this.goalId,
    this.milestoneId,
    this.habitId,
    this.date,
    this.time,
  });
}

// ── Add / Edit todo bottom sheet (通用) ───────────────────

class _TodoEditSheet extends StatefulWidget {
  final GoalService goalService;
  final HabitService habitService;
  final bool isAddMode;
  final bool isAutoGenerated;
  final String? initialTitle;
  final int? initialGoalId;
  final int? initialMilestoneId;
  final int? initialHabitId;
  final String? initialDate;
  final String? initialTime;
  final void Function(String title, int? goalId, int? milestoneId, int? habitId, String? date, String? time) onSave;

  const _TodoEditSheet({
    required this.goalService,
    required this.habitService,
    this.isAddMode = false,
    this.isAutoGenerated = false,
    this.initialTitle,
    this.initialGoalId,
    this.initialMilestoneId,
    this.initialHabitId,
    this.initialDate,
    this.initialTime,
    required this.onSave,
  });

  @override
  State<_TodoEditSheet> createState() => _TodoEditSheetState();
}

class _TodoEditSheetState extends State<_TodoEditSheet> {
  late final TextEditingController _controller;
  int? _selectedMilestoneId;
  int? _selectedHabitId;
  DateTime? _selectedDate;
  TimeOfDay? _selectedTime;
  List<Milestone> _milestones = [];
  List<Habit> _habits = [];
  Map<int, String> _goalNames = {};
  Map<int, String> _habitNames = {};
  Map<int, String> _milestoneNames = {};
  String? _specificHabitName; // 单独查询的习惯名称（用于自动生成待办）
  bool _loading = true;

  /// 是否已有父级（自动生成或有里程碑），此时关联字段为只读展示
  bool get _hasParent => widget.isAutoGenerated || widget.initialMilestoneId != null;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: widget.initialTitle ?? '');
    _selectedMilestoneId = widget.initialMilestoneId;
    _selectedHabitId = widget.initialHabitId;
    if (widget.initialDate != null) {
      try {
        _selectedDate = DateTime.parse(widget.initialDate!);
      } catch (_) {}
    }
    if (widget.initialTime != null) {
      final parts = widget.initialTime!.split(':');
      _selectedTime = TimeOfDay(
        hour: int.parse(parts[0]),
        minute: int.parse(parts[1]),
      );
    }
    _loadData();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  Future<void> _loadData() async {
    final goals = await widget.goalService.getActiveGoals();
    final allMilestones = <Milestone>[];
    final goalNamesMap = <int, String>{};
    final milestoneNamesMap = <int, String>{};
    for (final g in goals) {
      goalNamesMap[g.id!] = g.name;
      final ms = await widget.goalService.getMilestonesByGoal(g.id!);
      allMilestones.addAll(ms);
      for (final m in ms) {
        if (m.id != null) milestoneNamesMap[m.id!] = m.name;
      }
    }

    final allHabits = await widget.habitService.getAllHabits();
    final habitNamesMap = <int, String>{};
    for (final h in allHabits) {
      if (h.id != null) habitNamesMap[h.id!] = h.name;
    }

    // 如果有习惯ID但在批量映射中没找到，单独查询
    String? specificName;
    if (widget.initialHabitId != null && !habitNamesMap.containsKey(widget.initialHabitId)) {
      final h = await widget.habitService.getHabit(widget.initialHabitId!);
      if (h != null) specificName = h.name;
    }

    if (!mounted) return;
    setState(() {
      _milestones = allMilestones;
      _habits = allHabits;
      _goalNames = goalNamesMap;
      _milestoneNames = milestoneNamesMap;
      _habitNames = habitNamesMap;
      _specificHabitName = specificName;
      _loading = false;
    });
  }

  String get _timeString =>
      _selectedTime == null ? '' : '${_selectedTime!.hour.toString().padLeft(2, '0')}:${_selectedTime!.minute.toString().padLeft(2, '0')}';

  String? get _dateString {
    if (_selectedDate == null) return null;
    return '${_selectedDate!.year}-${_selectedDate!.month.toString().padLeft(2, '0')}-${_selectedDate!.day.toString().padLeft(2, '0')}';
  }

  /// 习惯名称：优先用加载的映射，其次用单独查询，最后 fallback 到 ID
  String get _resolvedHabitName {
    if (widget.initialHabitId == null) return '';
    if (_specificHabitName != null) return _specificHabitName!;
    return _habitNames[widget.initialHabitId] ?? '习惯 #${widget.initialHabitId}';
  }

  /// 里程碑名称：优先用加载的映射
  String get _resolvedMilestoneName {
    if (widget.initialMilestoneId == null) return '';
    return _milestoneNames[widget.initialMilestoneId] ?? '里程碑 #${widget.initialMilestoneId}';
  }

  void _handleSave() {
    if (_controller.text.trim().isEmpty) return;
    widget.onSave(
      _controller.text,
      _selectedMilestoneId != null ? _milestones.firstWhere(
        (m) => m.id == _selectedMilestoneId, orElse: () => Milestone(goalId: 0, name: ''),
      ).goalId : null,
      _selectedMilestoneId,
      _selectedHabitId,
      _dateString,
      _timeString.isEmpty ? null : _timeString,
    );
  }

  @override
  Widget build(BuildContext context) {
    final colorScheme = Theme.of(context).colorScheme;

    return Padding(
      padding: EdgeInsets.fromLTRB(16, 16, 16, MediaQuery.of(context).viewInsets.bottom + 16),
      child: SingleChildScrollView(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(widget.isAddMode ? '新建待办' : '编辑待办',
                style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 12),

            TextField(
              controller: _controller,
              autofocus: true,
              decoration: InputDecoration(
                hintText: '待办内容',
                border: const OutlineInputBorder(),
                suffixIcon: widget.isAutoGenerated
                    ? Icon(Icons.auto_mode, size: 18, color: colorScheme.primary.withValues(alpha: 0.4))
                    : null,
              ),
              onSubmitted: (_) => _handleSave(),
              readOnly: widget.isAutoGenerated,
            ),
            const SizedBox(height: 12),

            // 日期选择
            Text('日期（可选）', style: TextStyle(fontSize: 13, color: colorScheme.onSurface.withValues(alpha: 0.6))),
            const SizedBox(height: 4),
            InkWell(
              onTap: () async {
                final picked = await showDatePicker(
                  context: context,
                  initialDate: _selectedDate ?? DateTime.now(),
                  firstDate: DateTime.now().subtract(const Duration(days: 1)),
                  lastDate: DateTime.now().add(const Duration(days: 365)),
                );
                if (picked != null && mounted) {
                  setState(() => _selectedDate = picked);
                }
              },
              borderRadius: BorderRadius.circular(8),
              child: Container(
                width: double.infinity,
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
                decoration: BoxDecoration(
                  border: Border.all(color: colorScheme.outline.withValues(alpha: 0.5)),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  children: [
                    Icon(Icons.calendar_today, size: 20, color: colorScheme.onSurface.withValues(alpha: 0.6)),
                    const SizedBox(width: 10),
                    Text(
                      _selectedDate == null ? '今天' : '${_selectedDate!.year}-${_selectedDate!.month.toString().padLeft(2, '0')}-${_selectedDate!.day.toString().padLeft(2, '0')}',
                      style: TextStyle(
                        color: _selectedDate == null
                            ? colorScheme.onSurface.withValues(alpha: 0.4)
                            : null,
                      ),
                    ),
                    if (_selectedDate != null) ...[
                      const Spacer(),
                      GestureDetector(
                        onTap: () => setState(() => _selectedDate = null),
                        child: Icon(Icons.close, size: 18, color: colorScheme.onSurface.withValues(alpha: 0.4)),
                      ),
                    ],
                  ],
                ),
              ),
            ),
            const SizedBox(height: 12),

            // 时间选择
            Text('时间（可选）', style: TextStyle(fontSize: 13, color: colorScheme.onSurface.withValues(alpha: 0.6))),
            const SizedBox(height: 4),
            InkWell(
              onTap: () async {
                final picked = await showTimePicker(
                  context: context,
                  initialTime: _selectedTime ?? TimeOfDay.now(),
                );
                if (picked != null && mounted) {
                  setState(() => _selectedTime = picked);
                }
              },
              borderRadius: BorderRadius.circular(8),
              child: Container(
                width: double.infinity,
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
                decoration: BoxDecoration(
                  border: Border.all(color: colorScheme.outline.withValues(alpha: 0.5)),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Row(
                  children: [
                    Icon(Icons.schedule, size: 20, color: colorScheme.onSurface.withValues(alpha: 0.6)),
                    const SizedBox(width: 10),
                    Text(
                      _timeString.isEmpty ? '选择时间' : _timeString,
                      style: TextStyle(
                        color: _timeString.isEmpty
                            ? colorScheme.onSurface.withValues(alpha: 0.4)
                            : null,
                      ),
                    ),
                    if (_selectedTime != null) ...[
                      const Spacer(),
                      GestureDetector(
                        onTap: () => setState(() => _selectedTime = null),
                        child: Icon(Icons.close, size: 18, color: colorScheme.onSurface.withValues(alpha: 0.4)),
                      ),
                    ],
                  ],
                ),
              ),
            ),
            const SizedBox(height: 12),

            // ── 关联信息（仅已有关联的待办显示，纯手动待办不显示任何关联字段）──
            if (_hasParent) ...[
              if (widget.isAutoGenerated && widget.initialHabitId != null) ...[
                Text('所属习惯', style: TextStyle(fontSize: 13, color: colorScheme.onSurface.withValues(alpha: 0.6))),
                const SizedBox(height: 4),
                _ParentInfoRow(
                  icon: Icons.repeat,
                  iconColor: colorScheme.primary,
                  label: _resolvedHabitName,
                ),
              ] else if (widget.initialMilestoneId != null) ...[
                Text('所属里程碑', style: TextStyle(fontSize: 13, color: colorScheme.onSurface.withValues(alpha: 0.6))),
                const SizedBox(height: 4),
                _ParentInfoRow(
                  icon: Icons.flag,
                  iconColor: colorScheme.secondary,
                  label: _resolvedMilestoneName,
                  subtitle: widget.initialGoalId != null ? _goalNames[widget.initialGoalId] : null,
                ),
              ],
              const SizedBox(height: 16),
            ],

            SizedBox(
              width: double.infinity,
              child: FilledButton(
                onPressed: _handleSave,
                child: Text(widget.isAddMode ? '添加' : '保存'),
              ),
            ),

            // 父级关联提示
            if (widget.isAutoGenerated)
              Padding(
                padding: const EdgeInsets.only(top: 8),
                child: Text(
                  '此待办由习惯自动生成，仅可修改时间。',
                  style: TextStyle(fontSize: 11, color: Colors.orange.shade700),
                  textAlign: TextAlign.center,
                ),
              )
            else if (widget.initialMilestoneId != null)
              Padding(
                padding: const EdgeInsets.only(top: 8),
                child: Text(
                  '此待办归属于指定里程碑，仅可修改内容、时间和完成状态。',
                  style: TextStyle(fontSize: 11, color: Colors.orange.shade700),
                  textAlign: TextAlign.center,
                ),
              ),
          ],
        ),
      ),
    );
  }
}

/// 只读父级信息行组件
class _ParentInfoRow extends StatelessWidget {
  final IconData icon;
  final Color iconColor;
  final String label;
  final String? subtitle;

  const _ParentInfoRow({
    required this.icon,
    required this.iconColor,
    required this.label,
    this.subtitle,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
      decoration: BoxDecoration(
        border: Border.all(color: Theme.of(context).colorScheme.outline.withValues(alpha: 0.3)),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Row(
        children: [
          Icon(icon, size: 18, color: iconColor.withValues(alpha: 0.6)),
          const SizedBox(width: 8),
          Expanded(child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(label,
                  style: TextStyle(color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.7))),
              if (subtitle != null)
                Text(subtitle!,
                    style: TextStyle(fontSize: 11, color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.4))),
            ],
          )),
        ],
      ),
    );
  }
}
