import '../modules/database.dart';
import '../models/todo.dart';
import '../models/habit.dart';
import '../models/action_plan.dart';
import '../models/log_entry.dart';
import '../services/frequency_service.dart';

class TodoService {
  final AppDatabase _db;
  final FrequencyService _frequencyService;

  TodoService(this._db, this._frequencyService);

  /// 获取当天的 Todo 列表（含自动生成 + 手动创建）
  ///
  /// 自动生成逻辑：
  /// 1. 清理今天之前的自动 Todo
  /// 2. 遍历所有活跃习惯，判断今天是否训练日
  /// 3. 训练日习惯的行动项 → 自动 Todo
  /// 4. 如果习惯已完成（full/two_min），对应 Todo 标记为完成
  Future<List<Todo>> getTodayTodos() async {
    final today = _db.today();

    // 1. 生成今天的自动 Todo（幂等：先删后生成）
    await _generateAutoTodos(today);

    // 2. 返回今天的所有 Todo
    return _db.getTodosForDate(today);
  }

  /// 获取过期的手动 Todo（用于"顺延"功能）
  Future<List<Todo>> getExpiredManualTodos() async {
    return _db.getExpiredManualTodos(_db.today());
  }

  /// 获取指定里程碑下所有 Todo（不限日期）
  Future<List<Todo>> getTodosForMilestone(int milestoneId) async {
    await _generateAutoTodos(_db.today());
    return _db.getAllTodosForMilestone(milestoneId);
  }

  /// 获取未来的手动 Todo
  Future<List<Todo>> getFutureManualTodos() async {
    return _db.getFutureManualTodos(_db.today());
  }

  /// 顺延所有过期手动 Todo 到今天
  Future<int> postponeExpiredTodos() async {
    return _db.postponeExpiredManualTodos(_db.today());
  }

  /// 创建手动 Todo
  Future<Todo> createManualTodo({
    required String title,
    int? goalId,
    int? milestoneId,
    int? habitId,
    String? date,
    String? time,
  }) async {
    final todo = Todo(
      title: title,
      goalId: goalId,
      milestoneId: milestoneId,
      habitId: habitId,
      date: date ?? _db.today(),
      time: time,
      isAutoGenerated: false,
    );
    final id = await _db.insertTodo(todo);
    return todo.copyWith(id: id);
  }

  /// 切换 Todo 完成状态。
  ///
  /// 如果是自动生成的 Todo（关联了习惯），会同步更新 logs 表：
  /// - 勾选 → 创建打卡记录
  /// - 取消勾选 → 删除打卡记录
  Future<void> toggleTodo(int todoId, bool completed) async {
    final rows = await _db.db.query('todos', where: 'id = ?', whereArgs: [todoId]);
    if (rows.isEmpty) return;
    final todo = Todo.fromMap(rows.first);
    await _db.updateTodo(todo.copyWith(isCompleted: completed));

    // 自动生成的 Todo：同步更新 logs 表，实现双向同步
    if (todo.isAutoGenerated && todo.habitId != null) {
      final date = todo.date.isNotEmpty ? todo.date : _db.today();
      if (completed) {
        // 勾选 → 创建打卡记录（如果还没有）
        final existing = await _db.getLogForDate(todo.habitId!, date);
        if (existing == null) {
          await _db.insertLog(LogEntry(
            habitId: todo.habitId!,
            date: date,
            status: LogStatus.full,
          ));
        }
      } else {
        // 取消勾选 → 删除打卡记录，下次 _generateAutoTodos 不会强行标为完成
        await _db.db.delete('logs',
            where: 'habit_id = ? AND date = ?',
            whereArgs: [todo.habitId, date]);
      }
    }
  }

  /// 删除 Todo
  Future<void> deleteTodo(int id) async {
    await _db.deleteTodo(id);
  }

  /// 更新 Todo
  Future<void> updateTodo(Todo todo) async {
    await _db.updateTodo(todo);
  }

  // ── 自动生成逻辑 ─────────────────────────────────────

  /// 幂等地生成今天的自动 Todo：
  /// 删除今天的旧自动 Todo → 根据训练日重新生成
  /// 注意：会保留已有自动 Todo 的完成状态
  Future<void> _generateAutoTodos(String today) async {
    // 1. 读取今天已有自动 Todo 的完成状态（用于保留用户打的勾）
    final existingRows = await _db.db.query(
      'todos',
      where: "date = ? AND is_auto_generated = 1",
      whereArgs: [today],
      columns: ['id', 'habit_id', 'action_plan_id', 'is_completed'],
    );
    // 用 (habitId, actionPlanId) → isCompleted 做映射，保留完成状态
    final completedMap = <String, bool>{};
    for (final row in existingRows) {
      final key = '${row['habit_id']}_${row['action_plan_id']}';
      completedMap[key] = (row['is_completed'] as int?) == 1;
    }

    // 2. 删除今天的旧自动 Todo
    await _db.deleteAutoTodosForDate(today);

    // 3. 获取所有活跃习惯
    final habitRows = await _db.db.query('habits',
        where: 'archived = 0', orderBy: 'created ASC');
    final habits = habitRows.map(Habit.fromMap).toList();

    int sortOrder = 0;

    for (final habit in habits) {
      final habitId = habit.id!;

      // 判断今天是否训练日
      final logs = await _db.getLogsForHabit(habitId, limit: 30);
      final isTrainingDay = _frequencyService.isTrainingDaySync(habit, logs);

      if (!isTrainingDay) continue;

      // 获取该习惯的行动项
      final actions = await _db.getActionPlansForHabit(habitId);

      // 检查习惯今天的打卡状态
      final todayLog = await _db.getLogForDate(habitId, today);
      final habitCompleted = todayLog != null &&
          (todayLog.status == LogStatus.full ||
              todayLog.status == LogStatus.twoMin);
      final habitSkipped = todayLog != null && todayLog.status == LogStatus.skipped;

      // 跳过的习惯不生成 Todo
      if (habitSkipped) continue;

      if (actions.isEmpty) {
        // 习惯没有行动项，生成一个整体 Todo
        final key = '${habitId}_null';
        final wasCompleted = completedMap[key] ?? false;
        await _db.insertTodo(Todo(
          title: habit.name,
          habitId: habitId,
          date: today,
          time: habit.time,
          isAutoGenerated: true,
          isCompleted: habitCompleted || wasCompleted,
          sortOrder: sortOrder++,
        ));
      } else {
        // 为每个行动项生成 Todo
        for (final action in actions) {
          final actionId = action.id;
          final key = '${habitId}_${actionId}';
          final wasCompleted = completedMap[key] ?? false;

          // 检查行动项是否已在今天的 log 中标记完成
          bool actionCompleted = habitCompleted || wasCompleted;
          if (!actionCompleted && !wasCompleted && todayLog?.actionCompletions != null) {
            try {
              final decoded = todayLog!.actionCompletions!;
              if (decoded.contains('"${action.id}"')) {
                actionCompleted = true;
              }
            } catch (_) {}
          }

          await _db.insertTodo(Todo(
            title: action.name,
            habitId: habitId,
            actionPlanId: action.id,
            date: today,
            time: habit.time,
            isAutoGenerated: true,
            isCompleted: actionCompleted,
            sortOrder: sortOrder++,
          ));
        }
      }
    }
  }
}
