import 'dart:convert';
import '../modules/database.dart';
import '../models/todo.dart';
import '../models/habit.dart';
import '../models/action_plan.dart';
import '../models/log_entry.dart';
import '../services/frequency_service.dart';

class TodoService {
  final AppDatabase _db;
  final FrequencyService _frequencyService;

  TodoService(this._db, this._frequencyService);

  /// 获取当天的 Todo 列表（含自动生成 + 手动创建）
  ///
  /// 自动生成逻辑：
  /// 1. 清理今天之前的自动 Todo
  /// 2. 遍历所有活跃习惯，判断今天是否训练日
  /// 3. 训练日习惯的行动项 → 自动 Todo
  /// 4. 如果习惯已完成（full/two_min），对应 Todo 标记为完成
  Future<List<Todo>> getTodayTodos() async {
    final today = _db.today();

    // 1. 生成今天的自动 Todo（幂等：先删后生成）
    await _generateAutoTodos(today);

    // 2. 返回今天的所有 Todo
    return _db.getTodosForDate(today);
  }

  /// 获取过期的手动 Todo（用于"顺延"功能）
  Future<List<Todo>> getExpiredManualTodos() async {
    return _db.getExpiredManualTodos(_db.today());
  }

  /// 获取指定里程碑下所有 Todo（不限日期）
  Future<List<Todo>> getTodosForMilestone(int milestoneId) async {
    await _generateAutoTodos(_db.today());
    return _db.getAllTodosForMilestone(milestoneId);
  }

  /// 获取未来的手动 Todo
  Future<List<Todo>> getFutureManualTodos() async {
    return _db.getFutureManualTodos(_db.today());
  }

  /// 顺延所有过期手动 Todo 到今天
  Future<int> postponeExpiredTodos() async {
    return _db.postponeExpiredManualTodos(_db.today());
  }

  /// 创建手动 Todo
  Future<Todo> createManualTodo({
    required String title,
    int? goalId,
    int? milestoneId,
    int? habitId,
    String? date,
    String? time,
  }) async {
    final todo = Todo(
      title: title,
      goalId: goalId,
      milestoneId: milestoneId,
      habitId: habitId,
      date: date ?? _db.today(),
      time: time,
      isAutoGenerated: false,
    );
    final id = await _db.insertTodo(todo);
    return todo.copyWith(id: id);
  }

  /// 切换 Todo 完成状态。
  ///
  /// 自动生成的 Todo 同步更新 logs 表：
  /// - 习惯级 Todo（无 actionPlanId）：勾选→创建打卡，取消→删除打卡
  /// - 行动项 Todo（有 actionPlanId）：勾选/取消只影响 actionCompletions，
  ///   不会级联影响该习惯下的其他行动项
  Future<void> toggleTodo(int todoId, bool completed) async {
    final rows = await _db.db.query('todos', where: 'id = ?', whereArgs: [todoId]);
    if (rows.isEmpty) return;
    final todo = Todo.fromMap(rows.first);
    await _db.updateTodo(todo.copyWith(isCompleted: completed));

    if (!todo.isAutoGenerated || todo.habitId == null) return;

    final date = todo.date.isNotEmpty ? todo.date : _db.today();
    final existing = await _db.getLogForDate(todo.habitId!, date);

    if (todo.actionPlanId != null) {
      // ── 行动项级：通过 Map 格式管理（与习惯面一致）──
      final actionKey = '${todo.actionPlanId}';
      if (completed) {
        // 将该 action 加入 log（Map 格式：{"1": true}）
        if (existing == null) {
          await _db.insertLog(LogEntry(
            habitId: todo.habitId!,
            date: date,
            status: LogStatus.twoMin,
            actionCompletions: jsonEncode({actionKey: true}),
          ));
        } else {
          final map = _decodeActionCompletions(existing.actionCompletions);
          map[actionKey] = true;
          await _db.db.update('logs',
              {'action_completions': jsonEncode(map)},
              where: 'id = ?', whereArgs: [existing.id]);
        }
      } else {
        // 从 Map 中移除该 action
        if (existing != null) {
          final map = _decodeActionCompletions(existing.actionCompletions);
          map.remove(actionKey);
          if (map.isEmpty) {
            await _db.db.delete('logs',
                where: 'id = ?', whereArgs: [existing.id]);
          } else {
            await _db.db.update('logs',
                {'action_completions': jsonEncode(map)},
                where: 'id = ?', whereArgs: [existing.id]);
          }
        }
      }
    } else {
      // ── 习惯级：整习惯打卡/取消 ──
      if (completed) {
        if (existing == null) {
          await _db.insertLog(LogEntry(
            habitId: todo.habitId!,
            date: date,
            status: LogStatus.full,
          ));
        }
      } else {
        await _db.db.delete('logs',
            where: 'habit_id = ? AND date = ?',
            whereArgs: [todo.habitId, date]);
      }
    }
  }

  /// 删除 Todo
  Future<void> deleteTodo(int id) async {
    await _db.deleteTodo(id);
  }

  /// 更新 Todo
  Future<void> updateTodo(Todo todo) async {
    await _db.updateTodo(todo);
  }

  // ── 自动生成逻辑 ─────────────────────────────────────

  /// 幂等地生成今天的自动 Todo：
  /// 删除今天的旧自动 Todo → 根据训练日重新生成
  /// 注意：会保留已有自动 Todo 的完成状态
  Future<void> _generateAutoTodos(String today) async {
    // 1. 读取今天已有自动 Todo 的完成状态（用于保留用户打的勾）
    final existingRows = await _db.db.query(
      'todos',
      where: "date = ? AND is_auto_generated = 1",
      whereArgs: [today],
      columns: ['id', 'habit_id', 'action_plan_id', 'is_completed'],
    );
    // 用 (habitId, actionPlanId) → isCompleted 做映射，保留完成状态
    final completedMap = <String, bool>{};
    for (final row in existingRows) {
      final key = '${row['habit_id']}_${row['action_plan_id']}';
      completedMap[key] = (row['is_completed'] as int?) == 1;
    }

    // 2. 删除今天的旧自动 Todo
    await _db.deleteAutoTodosForDate(today);

    // 3. 获取所有活跃习惯
    final habitRows = await _db.db.query('habits',
        where: 'archived = 0', orderBy: 'created ASC');
    final habits = habitRows.map(Habit.fromMap).toList();

    int sortOrder = 0;

    for (final habit in habits) {
      final habitId = habit.id!;

      // 判断今天是否训练日
      final logs = await _db.getLogsForHabit(habitId, limit: 30);
      final isTrainingDay = _frequencyService.isTrainingDaySync(habit, logs);

      if (!isTrainingDay) continue;

      // 获取该习惯的行动项
      final actions = await _db.getActionPlansForHabit(habitId);

      // 检查习惯今天的打卡状态
      final todayLog = await _db.getLogForDate(habitId, today);
      final habitCompleted = todayLog != null &&
          (todayLog.status == LogStatus.full ||
              todayLog.status == LogStatus.twoMin);
      final habitSkipped = todayLog != null && todayLog.status == LogStatus.skipped;

      // 跳过的习惯不生成 Todo
      if (habitSkipped) continue;

      if (actions.isEmpty) {
        // 习惯没有行动项，生成一个整体 Todo
        final key = '${habitId}_null';
        final wasCompleted = completedMap[key] ?? false;
        await _db.insertTodo(Todo(
          title: habit.name,
          habitId: habitId,
          date: today,
          time: habit.time,
          isAutoGenerated: true,
          isCompleted: habitCompleted || wasCompleted,
          sortOrder: sortOrder++,
        ));
      } else {
        // 为每个行动项生成 Todo
        for (final action in actions) {
          final key = '${habitId}_${action.id}';
          final wasCompleted = completedMap[key] ?? false;

          // 行动项独立于习惯完成状态：由 wasCompleted 和 actionCompletions 决定，
          // 不继承 habitCompleted，保证每个行动项可以独立勾选/取消。
          bool actionCompleted = wasCompleted;
          if (!actionCompleted && todayLog?.actionCompletions != null) {
            try {
              final decoded = todayLog!.actionCompletions!;
              if (decoded.contains('"${action.id}"')) {
                actionCompleted = true;
              }
            } catch (_) {}
          }

          await _db.insertTodo(Todo(
            title: action.name,
            habitId: habitId,
            actionPlanId: action.id,
            date: today,
            time: habit.time,
            isAutoGenerated: true,
            isCompleted: actionCompleted,
            sortOrder: sortOrder++,
          ));
        }
      }
    }
  }

  /// 解析 actionCompletions JSON 为 Map（格式：{"actionPlanId": true, ...}）
  static Map<String, bool> _decodeActionCompletions(String? json) {
    if (json == null || json.isEmpty || json == '[]') return {};
    try {
      final decoded = jsonDecode(json) as Map<String, dynamic>;
      final result = <String, bool>{};
      decoded.forEach((k, v) => result[k] = v == true);
      return result;
    } catch (_) {
      return {};
    }
  }
}
