class Todo {
  final int? id;
  final String title;
  final int? goalId;
  final int? milestoneId;
  final int? habitId;
  final int? actionPlanId;
  final String date; // YYYY-MM-DD, which day this todo belongs to
  final String? time; // HH:mm optional time
  final bool isAutoGenerated;
  final bool isCompleted;
  final int sortOrder;
  final DateTime created;

  Todo({
    this.id,
    required this.title,
    this.goalId,
    this.milestoneId,
    this.habitId,
    this.actionPlanId,
    required this.date,
    this.time,
    this.isAutoGenerated = false,
    this.isCompleted = false,
    this.sortOrder = 0,
    DateTime? created,
  }) : created = created ?? DateTime.now();

  Map<String, dynamic> toMap() => {
        'id': id,
        'title': title,
        'goal_id': goalId,
        'milestone_id': milestoneId,
        'habit_id': habitId,
        'action_plan_id': actionPlanId,
        'date': date,
        'time': time,
        'is_auto_generated': isAutoGenerated ? 1 : 0,
        'is_completed': isCompleted ? 1 : 0,
        'sort_order': sortOrder,
        'created': created.toIso8601String(),
      };

  factory Todo.fromMap(Map<String, dynamic> map) => Todo(
        id: map['id'] as int?,
        title: map['title'] as String,
        goalId: map['goal_id'] as int?,
        milestoneId: map['milestone_id'] as int?,
        habitId: map['habit_id'] as int?,
        actionPlanId: map['action_plan_id'] as int?,
        date: map['date'] as String,
        time: map['time'] as String?,
        isAutoGenerated: (map['is_auto_generated'] as int?) == 1,
        isCompleted: (map['is_completed'] as int?) == 1,
        sortOrder: (map['sort_order'] as int?) ?? 0,
        created: DateTime.parse(map['created'] as String),
      );

  Todo copyWith({
    int? id,
    String? title,
    int? goalId,
    int? milestoneId,
    int? habitId,
    int? actionPlanId,
    String? date,
    String? time,
    bool? isAutoGenerated,
    bool? isCompleted,
    int? sortOrder,
    DateTime? created,
  }) =>
      Todo(
        id: id ?? this.id,
        title: title ?? this.title,
        goalId: goalId ?? this.goalId,
        milestoneId: milestoneId ?? this.milestoneId,
        habitId: habitId ?? this.habitId,
        actionPlanId: actionPlanId ?? this.actionPlanId,
        date: date ?? this.date,
        time: time ?? this.time,
        isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
        isCompleted: isCompleted ?? this.isCompleted,
        sortOrder: sortOrder ?? this.sortOrder,
        created: created ?? this.created,
      );
}
